version: '3.9'
services:
  web:
    restart: always
    build: ./back-end 
    volumes:
      - ./back-end:/var/www/
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: my-postgres-db
      DB_PORT: 5432
      DB_DATABASE: gazin
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    networks:
      - app-network

  db:
    image: postgres:12.0-alpine
    restart: always
    hostname: my-postgres-db
    environment:
      POSTGRES_DB: gazin
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - "./back-end/.docker/dbdata:/var/lib/postgresql/data"
    networks:
      - app-network

  nginx:
    build: ./back-end/.docker/nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./back-end:/var/www
    depends_on:
      - web
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
